spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1ns2vpiih5i62nao.mysql.rds.aliyuncs.com:3306/db_insurance
    username: uhealth
    password: Uhealth1@3456
  mvc:
    view:
      prefix:  classpath:/templates

#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/db_insurance
#    username: root
#    password: 950520



